---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: opscode-ubuntu-18.04-chef-14
    driver:
      box: bento/ubuntu-18.04
    provisioner:
      product_name: chef
      product_version: latest

suites:
  - name: default
    run_list:
      - recipe[haproxy::internal]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      haproxy:
        mode: 'http'
        default_backend: 'default'
        backends:
          - name: 'default'
            servers:
            - host: 'test-1.com'
              maxconn: 16
            - host: 'test-2.com'
              maxconn: 32
            app_port: 8080
            health_port: 8080
            ping_url: ''
