HTTP/1.0 504 Gateway Time-out
Cache-Control: no-cache
Connection: close
Content-Type: application/json

{
  "errors": [
    {
      "code": "HTTP_504",
      "message": "The server encountered a temporary error and could not complete your request. Please try again later.",
      "message_title": "504 Gateway Time-out",
      "message_severity": "error"
    }
  ]
}
